graph TD;

A[Pagina de Inicio] --> B[Pagina de Registro]
B --> C[Pagina de verificación de cuenta]
G --> I[Pagina de creación de noticias Consejal]
A --> D[Pagina de Inicio de Sesion]
D --> E[Pagina de Recuperación de Contraseña]
A --> G[Pagina de Noticias]
